export interface GameMeta {
  id: string;
  title: string;
  category: string;
  description: string;
  isPlayable: boolean;
}

export const GAMES: GameMeta[] = [
  { id: 'tictactoe', title: 'Tic-Tac-Toe', category: 'Logic', description: 'Classic 3x3 grid game against AI.', isPlayable: true },
  { id: 'connect4', title: 'Connect 4', category: 'Strategy', description: 'Drop discs to connect 4 in a row.', isPlayable: true },
  { id: 'wordchain', title: 'Word Chain', category: 'Word', description: 'Chain words using the last letter of the previous word.', isPlayable: true },
  { id: 'chess', title: 'Chess', category: 'Strategy', description: 'Classic game of kings and queens.', isPlayable: true },
  { id: 'checkers', title: 'Checkers', category: 'Strategy', description: 'Jump over opponent pieces to win.', isPlayable: true },
  { id: 'sudoku', title: 'Sudoku', category: 'Logic', description: 'Fill the 9x9 grid with numbers 1-9.', isPlayable: true },
  { id: '2048', title: '2048', category: 'Math', description: 'Slide tiles to combine them and reach 2048.', isPlayable: true },
  { id: 'memory', title: 'Memory Match', category: 'Memory', description: 'Find matching pairs of cards.', isPlayable: true },
  { id: 'minesweeper', title: 'Minesweeper', category: 'Logic', description: 'Clear the board without detonating hidden mines.', isPlayable: true },
  { id: 'wordle', title: 'Wordle Clone', category: 'Word', description: 'Guess the 5-letter word in 6 tries.', isPlayable: true },
  { id: 'hangman', title: 'Hangman', category: 'Word', description: 'Guess the word before the man is hanged.', isPlayable: true },
  { id: 'reversi', title: 'Reversi (Othello)', category: 'Strategy', description: 'Flip opponent discs to your color.', isPlayable: true },
  { id: 'battleship', title: 'Battleship', category: 'Strategy', description: 'Sink the AI fleet before it sinks yours.', isPlayable: true },
  { id: 'mastermind', title: 'Mastermind', category: 'Logic', description: 'Guess the secret color code.', isPlayable: true },
  { id: 'simonsays', title: 'Simon Says', category: 'Memory', description: 'Repeat the growing sequence of colors.', isPlayable: true },
  { id: 'anagrams', title: 'Anagrams', category: 'Word', description: 'Form words from scrambled letters.', isPlayable: true },
  { id: 'mathquiz', title: 'Math Quiz', category: 'Math', description: 'Solve math problems quickly.', isPlayable: true },
  { id: 'patternmatch', title: 'Pattern Match', category: 'Logic', description: 'Identify the next item in the pattern.', isPlayable: true },
  { id: 'trivia', title: 'Trivia', category: 'Knowledge', description: 'Answer general knowledge questions.', isPlayable: true },
  { id: 'gofish', title: 'Go Fish', category: 'Card', description: 'Collect sets of 4 matching cards.', isPlayable: true },
  { id: 'solitaire', title: 'Solitaire', category: 'Card', description: 'Classic Klondike Solitaire.', isPlayable: true },
  { id: 'mahjong', title: 'Mahjong', category: 'Puzzle', description: 'Match open pairs of identical tiles.', isPlayable: true },
  { id: 'slidingpuzzle', title: 'Sliding Puzzle', category: 'Puzzle', description: 'Slide tiles to assemble a picture.', isPlayable: true },
  { id: 'tetris', title: 'Tetris Clone', category: 'Puzzle', description: 'Fit falling blocks together.', isPlayable: true },
  { id: 'emojicharades', title: 'Emoji Charades', category: 'Word', description: 'Guess the phrase from AI emojis.', isPlayable: true },
  { id: 'pong', title: 'Pong', category: 'Action', description: 'Classic table tennis arcade game.', isPlayable: true },
  { id: 'breakout', title: 'Breakout', category: 'Action', description: 'Destroy bricks with a bouncing ball.', isPlayable: true },
  { id: 'spaceinvaders', title: 'Space Invaders', category: 'Action', description: 'Defend earth from alien ships.', isPlayable: true },
  { id: 'pacman', title: 'Pac-Man Clone', category: 'Action', description: 'Eat dots and avoid ghosts.', isPlayable: true },
  { id: 'flappybird', title: 'Flappy Bird Clone', category: 'Action', description: 'Navigate a bird through pipes.', isPlayable: true },
  { id: 'dinosaur', title: 'Dinosaur Run', category: 'Action', description: 'Jump over cacti as a T-Rex.', isPlayable: true },
  { id: 'typing', title: 'Typing Test', category: 'Skill', description: 'Type words as fast as you can.', isPlayable: true },
  { id: 'reaction', title: 'Reaction Time', category: 'Skill', description: 'Click as soon as the color changes.', isPlayable: true },
  { id: 'aimtrainer', title: 'Aim Trainer', category: 'Skill', description: 'Click targets quickly and accurately.', isPlayable: true },
  { id: 'chimp', title: 'Chimp Test', category: 'Memory', description: 'Remember the order of numbers.', isPlayable: true },
  { id: 'visualmemory', title: 'Visual Memory', category: 'Memory', description: 'Remember the pattern of white squares.', isPlayable: true },
  { id: 'numbermemory', title: 'Number Memory', category: 'Memory', description: 'Remember the longest number possible.', isPlayable: true },
  { id: 'verbalmemory', title: 'Verbal Memory', category: 'Memory', description: 'Keep track of words you have seen.', isPlayable: true },
  { id: 'sequence', title: 'Sequence Memory', category: 'Memory', description: 'Remember an increasingly long pattern.', isPlayable: true },
  { id: 'colorblind', title: 'Colorblind Test', category: 'Vision', description: 'Identify numbers in colored dots.', isPlayable: true },
  { id: 'pitch', title: 'Perfect Pitch', category: 'Audio', description: 'Identify musical notes by ear.', isPlayable: true },
  { id: 'rhythm', title: 'Rhythm Sense', category: 'Audio', description: 'Tap to the beat accurately.', isPlayable: true },
  { id: 'spatial', title: 'Spatial Reasoning', category: 'Logic', description: 'Mentally rotate 3D objects.', isPlayable: true },
  { id: 'cryptogram', title: 'Cryptogram', category: 'Word', description: 'Decode encrypted messages.', isPlayable: true },
  { id: 'crossword', title: 'Crossword', category: 'Word', description: 'Fill in words based on clues.', isPlayable: true },
  { id: 'wordsearch', title: 'Word Search', category: 'Word', description: 'Find hidden words in a grid.', isPlayable: true },
  { id: 'boggle', title: 'Boggle', category: 'Word', description: 'Find words in adjacent letters.', isPlayable: true },
  { id: 'scrabble', title: 'Scrabble Clone', category: 'Word', description: 'Form words on a board for points.', isPlayable: true },
  { id: 'dots', title: 'Dots and Boxes', category: 'Strategy', description: 'Connect dots to form boxes.', isPlayable: true },
  { id: 'nim', title: 'Nim', category: 'Strategy', description: 'Take turns removing objects from heaps.', isPlayable: true },
  { id: 'mancala', title: 'Mancala', category: 'Strategy', description: 'Sow seeds to capture the most.', isPlayable: true },
  { id: 'backgammon', title: 'Backgammon', category: 'Strategy', description: 'Move pieces according to dice rolls.', isPlayable: true },
];
