version: '3.8'

services:
  # The Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@db:5432/${DB_NAME:-playai}
      - JWT_SECRET=${JWT_SECRET:-please_change_this_secret_key_123}
    depends_on:
      db:
        condition: service_healthy

  # The Database
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER:-play-ai}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-play-ai}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U play-ai" ]
      interval: 10s
      timeout: 5s
      retries: 5
  # Nginx Proxy Manager (SSL & Reverse Proxy)
  proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '127.0.0.1:81:81'
      - '443:443'
    volumes:
      - ./npm-data:/data
      - ./npm-letsencrypt:/etc/letsencrypt
    depends_on:
      - app

volumes:
  pgdata:
  npm-data:
  npm-letsencrypt:
